theme: minima
title: Welcome and Good Luck
author: Jovi
email: private-info
description: > # this means to ignore newlines until "baseurl:"
  Not sure what you are looking for here, because neither do I.
  Just hope I'm doing this right. XD

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  joviT1100 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
